server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate /etc/letsencrypt/live/ludoradar.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ludoradar.mx/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 404;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.ludoradar.mx;

    include /etc/nginx/snippets/ludora-app.conf;

    ssl_certificate /etc/letsencrypt/live/ludoradar.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ludoradar.mx/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ludoradar.mx;

    ssl_certificate /etc/letsencrypt/live/ludoradar.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ludoradar.mx/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://www.ludoradar.mx$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ludora.bobbycrimson.com;

    ssl_certificate /etc/letsencrypt/live/ludora.bobbycrimson.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ludora.bobbycrimson.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://www.ludoradar.mx$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name ludoradar.mx www.ludoradar.mx;

    return 301 https://www.ludoradar.mx$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name ludora.bobbycrimson.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        try_files $uri =404;
    }

    location / {
        return 301 https://www.ludoradar.mx$request_uri;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 404;
}
