server {
    server_name ludora.bobbycrimson.com;

    include /etc/nginx/snippets/ludora-app.conf;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ludora.bobbycrimson.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ludora.bobbycrimson.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80;
    listen [::]:80;
    server_name ludora.bobbycrimson.com;
    return 301 https://ludora.bobbycrimson.com$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name ludoradar.mx www.ludoradar.mx;

    include /etc/nginx/snippets/ludora-app.conf;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 404;
}
